spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb
    username: root
    password: root@123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081


